Feature/pt 255
technologiesforaccessibility/osmintegrator-frontend pull request #103
Opened 2021-10-15 10:29 UTC by marcinniemirski

2021-10-15 17:38 UTC, luktar requested changes

2021-10-15 17:38 UTC, luktar commented on src/components/VersionLabel.jsx
> +        setErr(true);
zobacz jak w innych funkcjach REST jest przechwytywany wyjątek.
Stosujemy tam metodę `exception`.

2021-10-16 13:30 UTC, AdamSarach commented on src/components/VersionLabel.jsx
> +          headers: basicHeaders(),
wersja pojawia się także przy ekranach związanych z uwierzytelnianiem, endpoint nie powinien wymagać tokena, więc zamiast `basicHeaders()` można użyć `noTokenHeaders()`

2021-10-16 13:30 UTC, AdamSarach commented on src/components/VersionLabel.jsx
> +  useEffect(() => {
Sugestia odnośnie poniższego komentarza - element (Footer) występuje w 2 miejscach, więc zapytanie do api można wyciągnąć na zewnątrz, żeby wykonało się tylko raz, nie potrzebujemy tego pobierać przy każdym relogu

2021-10-19 07:23 UTC, luktar approved these changes

2021-10-28 04:44 UTC, jganczorz-revolve approved these changes

2021-10-29 04:58 UTC, jganczorz-revolve commented on src/components/contexts/UserContextProvider.jsx
> +  useEffect(() => {
Context który przechowuje stan reducera...
Plus z tego co wiem, wykorzystujemy ten numer wersji w tylko jednym komponencie?

Raczej wewnątrz każdego komponentu gdzie ma być wersja:
```
useEffect(() => {
  if (version) return;

  dispatch(getVersion());
}, [dispatch, version]);
```

2021-10-29 05:00 UTC, jganczorz-revolve approved these changes

2021-11-04 07:36 UTC, merged